"""enterprise_saas_entity_improvements

Revision ID: 0373602b81b4
Revises: 
Create Date: 2026-02-10 16:03:42.831639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0373602b81b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the invitestatus enum type in PostgreSQL first
    invitestatus_enum = postgresql.ENUM('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED', name='invitestatus', create_type=False)
    invitestatus_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('invitations', sa.Column('status', invitestatus_enum, nullable=False, server_default='PENDING'))
    op.add_column('invitations', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invitations', sa.Column('revoked_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'users', ['revoked_by'], ['id'], ondelete='SET NULL')
    op.add_column('organizations', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default='Unknown'))
    op.add_column('users', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('USER', 'ADMIN', 'AGENT', name='userrole'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'deactivated_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_superadmin')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'description')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'revoked_by')
    op.drop_column('invitations', 'revoked_at')
    op.drop_column('invitations', 'status')
    # Drop the invitestatus enum type
    postgresql.ENUM(name='invitestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
