"""Add OTP hash and failed attempts to MagicLinkToken

Revision ID: 7a160b943233
Revises: 0373602b81b4
Create Date: 2026-02-21 22:33:25.553486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a160b943233'
down_revision: Union[str, Sequence[str], None] = '0373602b81b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_magic_link_tokens', sa.Column('otp_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('auth_magic_link_tokens', sa.Column('failed_attempts', sa.Integer(), nullable=True))
    
    # Update existing rows to have default value of 0 for failed_attempts
    op.execute("UPDATE auth_magic_link_tokens SET failed_attempts = 0 WHERE failed_attempts IS NULL")
    
    # Now set it to NOT NULL
    op.alter_column('auth_magic_link_tokens', 'failed_attempts', nullable=False)
    
    op.create_index(op.f('ix_auth_magic_link_tokens_otp_hash'), 'auth_magic_link_tokens', ['otp_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_magic_link_tokens_otp_hash'), table_name='auth_magic_link_tokens')
    op.drop_column('auth_magic_link_tokens', 'failed_attempts')
    op.drop_column('auth_magic_link_tokens', 'otp_hash')
    # ### end Alembic commands ###
